### ISSUE TITLE
Routing to view a given source

### ISSUE THREAD

**Issue by cdeil** [gammapy/web-experiments#9]
At the moment I can go to
http://gammapy.github.io/web-experiments/
and select a source via the "source name" field and then the info for that source is displayed.

But the URL is still 
http://gammapy.github.io/web-experiments/

@kepta - Is there a way to do routing, so that it's possible to hit e.g.
http://gammapy.github.io/web-experiments/?cat=3fgl&source=42
and have the info for that source displayed?
Is this a lot of work or something that can be implemented relatively quickly?

Context: This is something I would like to have for
https://github.com/cdeil/hgps-webpage/blob/master/src/js/map.js#L81
there the tooltip displays the Fermi catalog name, and I'd like to link to this webpage (and in the future gamma-sky.org) to have the catalog info for this source listed.

**Comment by kepta** [comment]
sure, I will try to add a PR fixing this by today.

**Comment by kepta** [comment]
@cdeil the source name is generally of the format  `2FHL J0213.9-6949`.
how do you want me to interpret  `cat=3fgl&source=42`

**Comment by cdeil** [comment]
I think using the row index number for the source would be simplest, no?
Alternatively, we could do things like mapping "2FHL J0213.9-6949" to "2FHL_J0213.9m6949" for the URL.

**Comment by cdeil** [comment]
I have a question concerning routing from Javascript (which I've never implemented).
Does it have to be `BASE_URL?cat=3fgl&source=42` or is it also possible to have `BASE_URL/3fgl/42`?
This is only possible if the routing is done on the server, right?

**Comment by kepta** [comment]
No it can be done via router implementations. 
One example would be to use https://github.com/reactjs/react-router .

However, since I lack time ... I would some hot fix code, this won't be the best way to implement routing. But we can change it later.

**Comment by cdeil** [comment]
This has been implemented in #10.
Closing this feature request.
